defaults:
  - design/unit_randomized
  - estimators/naive
  - env/abtest

run:
  output_path: "output/test_out.csv"
  n_envs: 4
  n_steps: 10000
  estimate_every_n_steps: 1000
  seed: 42

env_params: {}
